# Generated by Django 4.2.6 on 2023-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='amigos_rel', to='login.user'),
        ),
    ]
