# Generated by Django 4.2.6 on 2023-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_amigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen perfil', null=True, upload_to='foto_perfil', verbose_name='Imagen Perfil'),
        ),
    ]
